# Generated by Django 6.0.2 on 2026-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_stalls", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
